### ISSUE TITLE
Feature Request: Add more detailed output

### ISSUE THREAD

**Issue by mikestecker** [swixpop/craft-locate#1]
I'd love to see more detailed output from the field so that I can better style the address returned.

Can you split out:
- Place Name
- Street 1
- Street 2
- City
- State
- Postal
- etc...

**Comment by swixpop** [comment]
The plugin is used to return `placeid` which is a textual identifier that uniquely identifies a place, and `lat` and `lng`. It's then up to you to use the these to query the Google Maps API.

The autocomplete field contents is just a string from Google. There is no failsafe way to parse this string to get the day you're looking for. The correct way to get this info is to make a [place details request to the Google Maps API](https://developers.google.com/maps/documentation/javascript/places#place_details_requests). This will give you the data you're looking for.
