### ISSUE TITLE
CSS overriding control panel

### ISSUE THREAD

**Issue by bleepsandblops** [swixpop/craft-locate#2]
Hi there,

Your css is overriding the control panel classes, example with `code`:
![screen shot 2018-07-30 at 18 47 39](https://user-images.githubusercontent.com/1942313/43410981-16454a44-9429-11e8-94df-8875128f2fff.png)
in my case styling the redactor `code` tag in a field edit view.

Thank you!

**Comment by swixpop** [comment]
Fixed in latest release. Thanks for catching that.
