### ISSUE TITLE
Error: Field must not contain emoji

### ISSUE THREAD

**Issue by elfacht** [swixpop/craft-locate#4]
Craft 3.0.28

This error occurs on names with **é** in it:

![screenshot 2018-10-26 um 00 09 17](https://user-images.githubusercontent.com/529443/47533282-7a747c00-d8b3-11e8-900c-95c84c1aae2b.jpg)

**Comment by elfacht** [comment]
This might be caused by a lot of ISO 8859-1 characters like `ß`, `ä` etc.

**Comment by Spifferiferfied** [comment]
I'm getting it when there are emoticons in the Google comments of the location.

**Comment by bartrylant** [comment]
Getting the same error. No emoji in the address field at all…

**Comment by elfacht** [comment]
When I try to save „Café Abseits“ in Bamberg, I'll get this `Database Expetion` now:

_SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8A 1...' for column 'keywords' at row 1
The SQL being executed was: INSERT INTO `bnb_searchindex` (`keywords`, `elementId`, `attribute`, `fieldId`, `siteId`) VALUES (' 49 89982379999999 10 90753559999996 cafe abseits poedeldorfer strasse bamberg deutschland chij9ao9shqjokcroquzsltbgsu 39 39 street_number poedeldorfer strasse poedeldorfer str route bamberg ba locality political oberfranken oberfranken administrative_area_level_2 political bayern by administrative_area_level_1 political deutschland de country political 96052 96052 postal_code poedeldorfer str 39 96052 bamberg deutschland poedeldorfer str 39 96052 bamberg deutschland 0951 303422 49 8998238 10 9075356 49 8984149197 10 9062272197 49 9011128803 10 9089251803 https maps gstatic com mapfiles place_api icons bar 71 png 0a2476424bb89b1b40b3fac04075f6aaa3e2eb2a 49 951 303422 cafe abseits 1 0 2330 23 30 1551652200000 0 0900 9 0 1551600000000 1 1400 14 0 1551704400000 1 1100 11 0 1551693600000 2 0030 0 30 1551742200000 1 1700 17 0 1551715200000 2 1400 14 0 1551790800000 2 1100 11 0 1551780000000 3 0030 0 30 1551828600000 2 1700 17 0 1551801600000 3 1400 14 0 1551272400000 3 1100 11 0 1551866400000 4 0030 0 30 1551310200000 3 1700 17 0 1551283200000 4 1400 14 0 1551358800000 4 1100 11 0 1551348000000 5 0030 0 30 1551396600000 4 1700 17 0 1551369600000 5 1400 14 0 1551445200000 5 0900 9 0 1551427200000 6 0030 0 30 1551483000000 5 1700 17 0 1551456000000 6 1400 14 0 1551531600000 6 0900 9 0 1551513600000 0 0030 0 30 1551569400000 6 1700 17 0 1551542400000 montag 11 00 14 00 uhr 17 00 00 30 uhr dienstag 11 00 14 00 uhr 17 00 00 30 uhr mittwoch 11 00 14 00 uhr 17 00 00 30 uhr donnerstag 11 00 14 00 uhr 17 00 00 30 uhr freitag 09 00 14 00 uhr 17 00 00 30 uhr samstag 09 00 14 00 uhr 17 00 00 30 uhr sonntag 09 00 23 30 uhr 2762 cafe abseits 4356 1784 calorie wise 1782 3024 bo kullmar 4032 3024 bo kullmar 4032 1920 cafe abseits 2560 720 maxi graemer 1280 5312 franz heinz 2988 2268 brian desvignes 4032 3024 einfach nutzer 4032 2322 karin dunger 4128 chij9ao9shqjokcroquzsltbgsu vwx5 w2 bamberg deutschland 8fxgvwx5 w2 4 4 chij9ao9shqjokcroquzsltbgsu der locke https www google com maps contrib 107349675902400540532 reviews de https lh4 googleusercontent com n6qca_iy87m aaaaaaaaaai aaaaaaaaaaa acevoqm_pk4p7ww2wklsebeocf6wt3clcw s128 c0x00000000 cc rp mo ba4 photo jpg 5 vor 2 wochen grandiose auswahl an fruehstuecksvariationen sehr grosse portionen und leckere speisen die bedienung war sehr freundlich und schnell wenn sich die gelegenheit ergibt werde ich auf jeden fall wieder hier fruehstuecken 1549886022 marie luise walter https www google com maps contrib 116066719322182434644 reviews de https lh6 googleusercontent com 8inqgsg4kzg aaaaaaaaaai aaaaaaaaabu i1ndqsblaj8 s128 c0x00000000 cc rp mo ba3 photo jpg 4 vor 3 wochen nette gemuetliche kneipe ausserhalb des stadtkerns naehe bahnhof gelegen uriges flair gemuetlicher biergarten und sehr offenes nettes personal machen einen besuch lohnenswert das essen ist mittelmaessig vielleicht eher fuer einen kleinen snack zwischen den bieren als fuer ein abendessen geeignet die bierauswahl ist riesig und fuer jeden etwas dabei auf dem bild zu sehen die bierprobe empfehlenswert fuer unentschlossene preise sind ebenfalls gut und stimmig toller laden besuch empfehlenswert v a wirklich im sommer wenn man im garten sitzen kann 1549435611 hans distler https www google com maps contrib 101362548495465368260 reviews de https lh3 googleusercontent com mhykumn0__o aaaaaaaaaai aaaaaaaaaaa acevoqpiu9hfyikyp3bkzdq9 bqumseazg s128 c0x00000000 cc rp mo ba4 photo jpg 3 vor 4 wochen ein sehr schoener garten im sommer wunderbar zum sitzen fruehstueck exzellent viele verschiedene biere immer einen besuch wert 1548800338 nicole https www google com maps contrib 110990628071469768129 reviews de https lh5 googleusercontent com nmh qp2f4go aaaaaaaaaai aaaaaaaaaaa acevoqmemyzxsn_ikxp16ef2iq8oem8htq s128 c0x00000000 cc rp mo ba3 photo jpg 4 vor einem monat nette kleine kneipe in der man auch gut essen kann 1546969708 i sevenkuka https www google com maps contrib 107466704940268690193 reviews de https lh6 googleusercontent com lykz4rp3jhs aaaaaaaaaai aaaaaaaaaaa acevoqp74cbzerpodfa a8tw5ttjrseohq s128 c0x00000000 cc rp mo photo jpg 5 vor 2 monaten aussen erst einmal unscheinbar aber fruehstueck im cafe xxl fuer 2 personen geordert so was erwartet man nicht in einer studentenkneipe sehr viel und schoen angerichtet dazu 2glaeser prosecco und frisch gepressten orangensaft einzig der cafe war nicht geschmack alles andere war toll 😊 1546029296 google bar point_of_interest establishment https maps google com cid=2673409010641251234 281 60 poedeldorfer strasse 39 bamberg http www abseits bamberg de 39 39 poedeldorfer strasse poedeldorfer str bamberg ba oberfranken oberfranken bayern by deutschland de 96052 96052 ', 1660, 'field', 259, 1) ON DUPLICATE KEY UPDATE `keywords`=' 49 89982379999999 10 90753559999996 cafe abseits poedeldorfer strasse bamberg deutschland chij9ao9shqjokcroquzsltbgsu 39 39 street_number poedeldorfer strasse poedeldorfer str route bamberg ba locality political oberfranken oberfranken administrative_area_level_2 political bayern by administrative_area_level_1 political deutschland de country political 96052 96052 postal_code poedeldorfer str 39 96052 bamberg deutschland poedeldorfer str 39 96052 bamberg deutschland 0951 303422 49 8998238 10 9075356 49 8984149197 10 9062272197 49 9011128803 10 9089251803 https maps gstatic com mapfiles place_api icons bar 71 png 0a2476424bb89b1b40b3fac04075f6aaa3e2eb2a 49 951 303422 cafe abseits 1 0 2330 23 30 1551652200000 0 0900 9 0 1551600000000 1 1400 14 0 1551704400000 1 1100 11 0 1551693600000 2 0030 0 30 1551742200000 1 1700 17 0 1551715200000 2 1400 14 0 1551790800000 2 1100 11 0 1551780000000 3 0030 0 30 1551828600000 2 1700 17 0 1551801600000 3 1400 14 0 1551272400000 3 1100 11 0 1551866400000 4 0030 0 30 1551310200000 3 1700 17 0 1551283200000 4 1400 14 0 1551358800000 4 1100 11 0 1551348000000 5 0030 0 30 1551396600000 4 1700 17 0 1551369600000 5 1400 14 0 1551445200000 5 0900 9 0 1551427200000 6 0030 0 30 1551483000000 5 1700 17 0 1551456000000 6 1400 14 0 1551531600000 6 0900 9 0 1551513600000 0 0030 0 30 1551569400000 6 1700 17 0 1551542400000 montag 11 00 14 00 uhr 17 00 00 30 uhr dienstag 11 00 14 00 uhr 17 00 00 30 uhr mittwoch 11 00 14 00 uhr 17 00 00 30 uhr donnerstag 11 00 14 00 uhr 17 00 00 30 uhr freitag 09 00 14 00 uhr 17 00 00 30 uhr samstag 09 00 14 00 uhr 17 00 00 30 uhr sonntag 09 00 23 30 uhr 2762 cafe abseits 4356 1784 calorie wise 1782 3024 bo kullmar 4032 3024 bo kullmar 4032 1920 cafe abseits 2560 720 maxi graemer 1280 5312 franz heinz 2988 2268 brian desvignes 4032 3024 einfach nutzer 4032 2322 karin dunger 4128 chij9ao9shqjokcroquzsltbgsu vwx5 w2 bamberg deutschland 8fxgvwx5 w2 4 4 chij9ao9shqjokcroquzsltbgsu der locke https www google com maps contrib 107349675902400540532 reviews de https lh4 googleusercontent com n6qca_iy87m aaaaaaaaaai aaaaaaaaaaa acevoqm_pk4p7ww2wklsebeocf6wt3clcw s128 c0x00000000 cc rp mo ba4 photo jpg 5 vor 2 wochen grandiose auswahl an fruehstuecksvariationen sehr grosse portionen und leckere speisen die bedienung war sehr freundlich und schnell wenn sich die gelegenheit ergibt werde ich auf jeden fall wieder hier fruehstuecken 1549886022 marie luise walter https www google com maps contrib 116066719322182434644 reviews de https lh6 googleusercontent com 8inqgsg4kzg aaaaaaaaaai aaaaaaaaabu i1ndqsblaj8 s128 c0x00000000 cc rp mo ba3 photo jpg 4 vor 3 wochen nette gemuetliche kneipe ausserhalb des stadtkerns naehe bahnhof gelegen uriges flair gemuetlicher biergarten und sehr offenes nettes personal machen einen besuch lohnenswert das essen ist mittelmaessig vielleicht eher fuer einen kleinen snack zwischen den bieren als fuer ein abendessen geeignet die bierauswahl ist riesig und fuer jeden etwas dabei auf dem bild zu sehen die bierprobe empfehlenswert fuer unentschlossene preise sind ebenfalls gut und stimmig toller laden besuch empfehlenswert v a wirklich im sommer wenn man im garten sitzen kann 1549435611 hans distler https www google com maps contrib 101362548495465368260 reviews de https lh3 googleusercontent com mhykumn0__o aaaaaaaaaai aaaaaaaaaaa acevoqpiu9hfyikyp3bkzdq9 bqumseazg s128 c0x00000000 cc rp mo ba4 photo jpg 3 vor 4 wochen ein sehr schoener garten im sommer wunderbar zum sitzen fruehstueck exzellent viele verschiedene biere immer einen besuch wert 1548800338 nicole https www google com maps contrib 110990628071469768129 reviews de https lh5 googleusercontent com nmh qp2f4go aaaaaaaaaai aaaaaaaaaaa acevoqmemyzxsn_ikxp16ef2iq8oem8htq s128 c0x00000000 cc rp mo ba3 photo jpg 4 vor einem monat nette kleine kneipe in der man auch gut essen kann 1546969708 i sevenkuka https www google com maps contrib 107466704940268690193 reviews de https lh6 googleusercontent com lykz4rp3jhs aaaaaaaaaai aaaaaaaaaaa acevoqp74cbzerpodfa a8tw5ttjrseohq s128 c0x00000000 cc rp mo photo jpg 5 vor 2 monaten aussen erst einmal unscheinbar aber fruehstueck im cafe xxl fuer 2 personen geordert so was erwartet man nicht in einer studentenkneipe sehr viel und schoen angerichtet dazu 2glaeser prosecco und frisch gepressten orangensaft einzig der cafe war nicht geschmack alles andere war toll 😊 1546029296 google bar point_of_interest establishment https maps google com cid=2673409010641251234 281 60 poedeldorfer strasse 39 bamberg http www abseits bamberg de 39 39 poedeldorfer strasse poedeldorfer str bamberg ba oberfranken oberfranken bayern by deutschland de 96052 96052 '_

**Comment by swixpop** [comment]
@elfacht Can you try implementing this and see if you get the same error? https://github.com/swixpop/craft-locate/pull/7/commits/174e922ec3af9a50c7e9efd654df22bed5e1b4fb
