### ISSUE TITLE
Error when user enters in field

### ISSUE THREAD

**Issue by bartrylant** [swixpop/craft-locate#5]
When a user presses the enter key after entering an address, the entry form gets submitted and an error occurs:

yii\base\ErrorException: Invalid argument supplied for foreach() in /srv/users/***/apps/***-app/vendor/swixpop/locate/src/fields/LocateField.php:129

**Comment by jdsimcoe** [comment]
I'm getting precisely the same error code when trying to save a location field.

**Comment by bartrylant** [comment]
Any news?
